name: Create Website Release package

on:
  push:
    branches:
      - github-workflows
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Install Jekyll
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle update --bundler

      - name: Build site
        run: bundle exec jekyll build

      - name: Create version.json
        run: 'echo "{ \"version\": \"${{ env.RELEASE_VERSION }}\", \"git_ref\": \"$GITHUB_SHA\"}" > ./_site/version.json'

      - name: Rename folder
        run: mv _site public

      - name: Create tar
        run: tar -czf cm_website_${{ env.RELEASE_VERSION }}.tar.gz ./public

      - name: Upload release tar
        uses: actions/upload-artifact@v2
        with:
          name: cm_website_${{ env.RELEASE_VERSION }}
          path: cm_website_${{ env.RELEASE_VERSION }}.tar.gz
